// LOCALHOST
###
GET http://localhost:8080/
###
POST http://localhost:8080/api/auth/login/
Content-Type: application/json

{
  "username": "jackkirby",
  "password": "secret"
}
###
GET http://localhost:8080/api/auth/logout/
###
GET http://localhost:8080/api/users/
###
GET http://localhost:8080/api/users/6604b8139399fc74ed9353a0
###
POST http://localhost:8080/api/users
Content-Type: application/json

{
   "username": "stanlee2",
   "email": "stanlee@marvel.com",
   "phone": "+15412440891",
   "role": "Admin"
}
###
POST http://localhost:8080/api/users
Content-Type: application/json

{
   "username": "joelcannon",
   "email": "joelcannon@gmail.com",
      "phone": "+15412440896",
   "role": "Editor"
}

###
DELETE http://localhost:8080/api/users/
###
PUT http://localhost:8080/api/users/65f686bb683dbbdb77013770
Content-Type: application/json

{
   "username": "joelC",
   "role": "Viewer"
}

###
PATCH http://localhost:8080/api/users/6604b8139399fc74ed9353a0/toggleActiveStatus
Content-Type: application/json


// RENDER.COM
###
GET https://superheros-6636.onrender.com/
###
POST https://superheros-6636.onrender.com/api/auth/login/
Content-Type: application/json

{
  "username": "jackkirby",
  "password": "secret"
}
###
GET https://superheros-6636.onrender.com/api/auth/logout/
###
GET https://superheros-6636.onrender.com/api/users/
###
GET https://superheros-6636.onrender.com/api/users/6604b8139399fc74ed9353a0
###
POST https://superheros-6636.onrender.com/api/users
Content-Type: application/json

{
   "username": "stanlee",
   "email": "stanlee@marvel.com",
   "phone": "+15412440891",
   "role": "Admin"
}
###
POST https://superheros-6636.onrender.com/api/users
Content-Type: application/json

{
   "username": "joelcannon",
   "email": "joelcannon@gmail.com",
   "phone": "+15412440896",
   "role": "Editor"
}

###
DELETE https://superheros-6636.onrender.com/api/users/
###
PUT https://superheros-6636.onrender.com/api/users/65f686bb683dbbdb77013770
Content-Type: application/json

{
   "username": "joelC",
   "role": "Viewer"
}

###
PATCH https://superheros-6636.onrender.com/api/users/6604b8139399fc74ed9353a0/toggleActiveStatus
Content-Type: application/json
