// LOCALHOST
###
GET http://localhost:8080/
###
GET http://localhost:8080/api/auth/login/
###
GET http://localhost:8080/api/auth/logout/
###
GET http://localhost:8080/api/users/
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
GET http://localhost:8080/api/users/65fa431d942aa0637e1f34b5
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
POST http://localhost:8080/api/users
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

{
   "username": "joel",
   "email": "joelcannon@mac.co",
   "phone": "+15412440898",
   "role": "Admin"
}
###
POST http://localhost:8080/api/users
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

{
   "username": "joelcannon",
   "email": "joelcannon@gmail.com",
      "phone": "+15412440896",
   "role": "Operator"
}

###
DELETE http://localhost:8080/api/users/
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
PUT http://localhost:8080/api/users/65f686bb683dbbdb77013770
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

{
   "username": "joelC",
   "role": "Viewer"
}

###
PATCH http://localhost:8080/api/users/65fa4317942aa0637e1f34b3/toggleActiveStatus
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N


// RENDER.COM
###
GET https://cse341-w4-h46g.onrender.com//api/auth/login/
###
GET https://cse341-w4-h46g.onrender.com//api/auth/logout/
###
GET https://cse341-w4-h46g.onrender.com//api/users/
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
GET https://cse341-w4-h46g.onrender.com//api/users/65f68a1a683dbbdb7701378f
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
POST https://cse341-w4-h46g.onrender.com//api/users
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

{
   "username": "joel",
   "email": "joelcannon@mac.co",
      "phone": "+15412440898",
"role": "Super Admin"
}

###
POST https://cse341-w4-h46g.onrender.com//api/users
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

{
   "username": "joelcannon",
   "email": "joelcannon@gmail.com",
      "phone": "+15412440896",
"role": "Operator"
}
###
DELETE https://cse341-w4-h46g.onrender.com//api/users/65f68a1a683dbbdb7701378f
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
###
PUT https://cse341-w4-h46g.onrender.com//api/users/65f68a1a683dbbdb7701378f
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N

{
   "username": "joelC",
   "role": "Viewer"
}

###
PATCH https://cse341-w4-h46g.onrender.com//api/users/65f68a1a683dbbdb7701378f/toggleActiveStatus
Content-Type: application/json
apiKey: Ezl0961tEpx2UxTZ5v2uKFK91qdNAr5npRlMT1zLcE3Mg68Xwaj3N8Dyp1R8IvFenrVwHRllOUxF0Og00l0m9NcaYMtH6Bpgdv7N
